import type { Metadata } from "next";
import { Inter, Arvo } from "next/font/google";
import "./globals.css";

const arvo = Arvo({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Santiago's Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={arvo.className}>
        {children}
      </body>
    </html>
  );
}
